=== andrew-hipp/vplants-legacy/vplants-web/htdocs/metadata/vpindex.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<!--Generated by XML Authority. Conforms to w3c http://www.w3.org/2001/XMLSchema-->
<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema">
	<!--Index Layer-->
	
	<xsd:element name = "link">
		<xsd:simpleType>
			<xsd:restriction base = "xsd:anyURI">
				<xsd:pattern value = "http://.*"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name = "herbcd" type = "xsd:string"/>
	<xsd:element name = "index">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "herbcd"/>
				<xsd:element ref = "taxon"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "taxon">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "link" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== andrew-hipp/vplants-legacy/vplants-web/htdocs/metadata/vpindex.xml
<?xml version = "1.0" encoding = "UTF-8"?>

<!--Index Layer-->
<index xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "http://www.vplants.org/metadata/vpindex.xsd">
	<herbcd>MOR</herbcd>
	<taxon>
		<link>http://www.mortonarb.org/vplants/NameLookup?nameid=2</link>
		<link>http://www.mortonarb.org/vplants/NameLookup?nameid=32</link>
		<link>http://www.mortonarb.org/vplants/NameLookup?nameid=42</link>
		<link>http://www.mortonarb.org/vplants/NameLookup?nameid=51</link>
		<link>http://www.mortonarb.org/vplants/NameLookup?nameid=64</link>
		<link>http://www.mortonarb.org/vplants/NameLookup?nameid=124</link>
		<link>http://www.mortonarb.org/vplants/NameLookup?nameid=654</link>
		<link>http://www.mortonarb.org/vplants/NameLookup?nameid=678</link>
		<link>http://www.mortonarb.org/vplants/NameLookup?nameid=697</link>
		<link>http://www.mortonarb.org/vplants/NameLookup?nameid=698</link>
	</taxon>
</index>

=== andrew-hipp/vplants-legacy/trunk/vplants-web/webapps/xsql/metadata/old/small.orig.xml
<?xml version="1.0" encoding="UTF-8" ?> 
<index xsi:noNamespaceSchemaLocation="http://www.vplants.org/metadata/vpindex.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<herbcd>MOR</herbcd> 
 <taxon>
  <link>http://redwood.mortonarb.org/xsql/metadata/vphdr.xsql?id=5</link> 
  <link>http://redwood.mortonarb.org/xsql/metadata/vphdr.xsql?id=6</link> 
  <link>http://redwood.mortonarb.org/xsql/metadata/vphdr.xsql?id=7</link> 
  <link>http://redwood.mortonarb.org/xsql/metadata/vphdr.xsql?id=9</link> 
  <link>http://redwood.mortonarb.org/xsql/metadata/vphdr.xsql?id=10</link> 
  <link>http://redwood.mortonarb.org/xsql/metadata/vphdr.xsql?id=11</link> 
  <link>http://redwood.mortonarb.org/xsql/metadata/vphdr.xsql?id=12</link> 
  <link>http://redwood.mortonarb.org/xsql/metadata/vphdr.xsql?id=13</link> 
 </taxon>
</index>

=== andrew-hipp/vplants-legacy/vplants-species-transmogrifier/speciesTransformer-v1/speciesTransformer-v1.0/DEST/JS2/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<index xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.vplants.org/metadata/vpindex.xsd"><herbcd>F</herbcd><taxon><link>http://vplants.mortonarb.org/fm/data/I/IOPI.xml</link><link>http://vplants.mortonarb.org/fm/data/I/ISTI.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LECA5.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LEDE.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LEDR.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LELA2.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LEPE2.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LERU.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LESA2.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LEVI3.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LEGR2.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LOMA.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LUAN.xml</link><link>http://vplants.mortonarb.org/fm/data/M/MAAF.xml</link><link>http://vplants.mortonarb.org/fm/data/M/MAIN4.xml</link><link>http://vplants.mortonarb.org/fm/data/V/VP-136.xml</link><link>http://vplants.mortonarb.org/fm/data/N/NEPA3.xml</link><link>http://vplants.mortonarb.org/fm/data/R/RARA2.xml</link><link>http://vplants.mortonarb.org/fm/data/R/RASA2.xml</link><link>http://vplants.mortonarb.org/fm/data/V/VP-62.xml</link><link>http://vplants.mortonarb.org/fm/data/R/RARU.xml</link></taxon></index>

=== andrew-hipp/vplants-legacy/vplants-species-transmogrifier/speciesTransformer-v1/speciesTransformer-v1.0/DEST/JS_transformer_Trial/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<index xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.vplants.org/metadata/vpindex.xsd"><herbcd>MOR</herbcd><taxon><link>http://vplants.mortonarb.org/fm/data/F/FOIN3.xml</link><link>http://vplants.mortonarb.org/fm/data/F/FRAM2.xml</link><link>http://vplants.mortonarb.org/fm/data/F/FRNI.xml</link><link>http://vplants.mortonarb.org/fm/data/F/FRPE.xml</link><link>http://vplants.mortonarb.org/fm/data/F/FRPR.xml</link><link>http://vplants.mortonarb.org/fm/data/F/FRQU.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LIOB.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LIVU.xml</link><link>http://vplants.mortonarb.org/fm/data/V/VP-99.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SYVU.xml</link><link>http://vplants.mortonarb.org/fm/data/V/VP-100.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LALA.xml</link><link>http://vplants.mortonarb.org/fm/data/P/PIMA.xml</link><link>http://vplants.mortonarb.org/fm/data/P/PIBA2.xml</link><link>http://vplants.mortonarb.org/fm/data/P/PINI.xml</link><link>http://vplants.mortonarb.org/fm/data/P/PIRE.xml</link><link>http://vplants.mortonarb.org/fm/data/P/PIRI.xml</link><link>http://vplants.mortonarb.org/fm/data/P/PIST.xml</link><link>http://vplants.mortonarb.org/fm/data/P/PISY.xml</link><link>http://vplants.mortonarb.org/fm/data/P/PIVI2.xml</link><link>http://vplants.mortonarb.org/fm/data/T/TSCA.xml</link><link>http://vplants.mortonarb.org/fm/data/P/POAL7.xml</link><link>http://vplants.mortonarb.org/fm/data/P/POBA2.xml</link><link>http://vplants.mortonarb.org/fm/data/P/PODE3.xml</link><link>http://vplants.mortonarb.org/fm/data/P/POGR4.xml</link><link>http://vplants.mortonarb.org/fm/data/P/POHE4.xml</link><link>http://vplants.mortonarb.org/fm/data/P/PONI.xml</link><link>http://vplants.mortonarb.org/fm/data/P/POTR5.xml</link><link>http://vplants.mortonarb.org/fm/data/P/POCA14.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SAAL2.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SAAM2.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SABE2.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SACA4.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SACA22.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SACI.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SACO3.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SADI.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SAER.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SAFR.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SAHUH.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SAHUT.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SAHU2.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SAIN3.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SALU.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SAMYM.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SANI.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SAPE2.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SAPE4.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SAPE5.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SAPU2.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SASE.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SASE2.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SAVI2.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SACO10.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SAGL3.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SAPE12.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SARU3.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SASE10.xml</link><link>http://vplants.mortonarb.org/fm/data/T/TIAMH.xml</link><link>http://vplants.mortonarb.org/fm/data/T/TIAM.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CEOC.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CETE.xml</link><link>http://vplants.mortonarb.org/fm/data/U/ULAM.xml</link><link>http://vplants.mortonarb.org/fm/data/U/ULPR.xml</link><link>http://vplants.mortonarb.org/fm/data/U/ULPU.xml</link><link>http://vplants.mortonarb.org/fm/data/U/ULRU.xml</link><link>http://vplants.mortonarb.org/fm/data/U/ULTH.xml</link><link>http://vplants.mortonarb.org/fm/data/U/ULNO.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SAPU4.xml</link><link>http://vplants.mortonarb.org/fm/data/C/COUM.xml</link><link>http://vplants.mortonarb.org/fm/data/C/COUMU.xml</link><link>http://vplants.mortonarb.org/fm/data/S/SCPA2.xml</link><link>http://vplants.mortonarb.org/fm/data/E/ERAQ2.xml</link><link>http://vplants.mortonarb.org/fm/data/B/BRSC.xml</link><link>http://vplants.mortonarb.org/fm/data/A/ALPE4.xml</link><link>http://vplants.mortonarb.org/fm/data/A/ALAL3.xml</link><link>http://vplants.mortonarb.org/fm/data/V/VP-132.xml</link><link>http://vplants.mortonarb.org/fm/data/A/ARTH.xml</link><link>http://vplants.mortonarb.org/fm/data/A/ARHIA.xml</link><link>http://vplants.mortonarb.org/fm/data/A/ARHI.xml</link><link>http://vplants.mortonarb.org/fm/data/A/ARRU4.xml</link><link>http://vplants.mortonarb.org/fm/data/B/BAVE.xml</link><link>http://vplants.mortonarb.org/fm/data/V/VP-64.xml</link><link>http://vplants.mortonarb.org/fm/data/B/BAVU.xml</link><link>http://vplants.mortonarb.org/fm/data/B/BEIN2.xml</link><link>http://vplants.mortonarb.org/fm/data/V/VP-133.xml</link><link>http://vplants.mortonarb.org/fm/data/B/BODI4.xml</link><link>http://vplants.mortonarb.org/fm/data/B/BODR.xml</link><link>http://vplants.mortonarb.org/fm/data/V/VP-134.xml</link><link>http://vplants.mortonarb.org/fm/data/V/VP-177.xml</link><link>http://vplants.mortonarb.org/fm/data/V/VP-174.xml</link><link>http://vplants.mortonarb.org/fm/data/B/BRJU.xml</link><link>http://vplants.mortonarb.org/fm/data/B/BRNA.xml</link><link>http://vplants.mortonarb.org/fm/data/B/BRNI.xml</link><link>http://vplants.mortonarb.org/fm/data/B/BRRA.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CAEDE2.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CAEDL2.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CAED.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CAMI2.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CASA2.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CABU2.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CABU3.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CACO26.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CADI10.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CADO.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CAHI3.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CAPAA2.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CAPA12.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CAPE3.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CAPRP2.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CAPR3.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CAPU6.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CHTE2.xml</link><link>http://vplants.mortonarb.org/fm/data/C/COMOR.xml</link><link>http://vplants.mortonarb.org/fm/data/C/COOR.xml</link><link>http://vplants.mortonarb.org/fm/data/C/CODI6.xml</link><link>http://vplants.mortonarb.org/fm/data/D/DEPIB.xml</link><link>http://vplants.mortonarb.org/fm/data/D/DESO2.xml</link><link>http://vplants.mortonarb.org/fm/data/D/DIMU2.xml</link><link>http://vplants.mortonarb.org/fm/data/D/DITE4.xml</link><link>http://vplants.mortonarb.org/fm/data/D/DRBR.xml</link><link>http://vplants.mortonarb.org/fm/data/D/DRRE2.xml</link><link>http://vplants.mortonarb.org/fm/data/D/DRVE2.xml</link><link>http://vplants.mortonarb.org/fm/data/E/ERGA.xml</link><link>http://vplants.mortonarb.org/fm/data/E/ERCH9.xml</link><link>http://vplants.mortonarb.org/fm/data/E/ERHI8.xml</link><link>http://vplants.mortonarb.org/fm/data/E/ERIN7.xml</link><link>http://vplants.mortonarb.org/fm/data/E/ERRE4.xml</link><link>http://vplants.mortonarb.org/fm/data/H/HEMA3.xml</link><link>http://vplants.mortonarb.org/fm/data/I/IOPI.xml</link><link>http://vplants.mortonarb.org/fm/data/I/ISTI.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LECA5.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LEDE.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LEDR.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LELA2.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LEPE2.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LERU.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LESA2.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LEVI3.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LEGR2.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LOMA.xml</link><link>http://vplants.mortonarb.org/fm/data/L/LUAN.xml</link><link>http://vplants.mortonarb.org/fm/data/M/MAAF.xml</link><link>http://vplants.mortonarb.org/fm/data/M/MAIN4.xml</link><link>http://vplants.mortonarb.org/fm/data/V/VP-136.xml</link><link>http://vplants.mortonarb.org/fm/data/N/NEPA3.xml</link><link>http://vplants.mortonarb.org/fm/data/R/RARA2.xml</link><link>http://vplants.mortonarb.org/fm/data/R/RASA2.xml</link><link>http://vplants.mortonarb.org/fm/data/V/VP-62.xml</link><link>http://vplants.mortonarb.org/fm/data/R/RARU.xml</link></taxon></index>
