=== andrew-hipp/vplants-legacy/vplants-web/htdocs/metadata/vptaxon.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<!--Generated by XML Authority. Conforms to w3c http://www.w3.org/2001/XMLSchema-->
<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema">
	<!-- Taxon Layer-->
	
	
	<!-- ***********************VPHDR************************ -->
	
	<xsd:element name = "taxon">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "namecd"/>
				<xsd:element ref = "common" minOccurs = "0" maxOccurs = "unbounded"/>
				<xsd:element ref = "spm" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "common" type = "xsd:string"/>
	<xsd:element name = "spm">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "spmid"/>
				<xsd:element ref = "updttm"/>
				<xsd:element ref = "link" minOccurs = "0"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "spmid" type = "xsd:string"/>
	<xsd:element name = "updttm">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "month"/>
				<xsd:element ref = "day"/>
				<xsd:element ref = "year"/>
				<xsd:element ref = "hour"/>
				<xsd:element ref = "min"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "link">
		<xsd:simpleType>
			<xsd:restriction base = "xsd:anyURI">
				<xsd:pattern value = "http://.*"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name = "namecd" type = "xsd:string"/>
	<xsd:element name = "month" type = "xsd:integer"/>
	<xsd:element name = "day" type = "xsd:integer"/>
	<xsd:element name = "year" type = "xsd:integer"/>
	<xsd:element name = "hour" type = "xsd:integer"/>
	<xsd:element name = "min" type = "xsd:integer"/>
</xsd:schema>

=== andrew-hipp/vplants-legacy/vplants-web/htdocs/metadata/vptaxon.xml
<?xml version = "1.0" encoding = "UTF-8"?>

<!--Taxon Layer-->
<taxon xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "http://www.vplants.org/metadata/vptaxon.xsd">
	<namecd>BALE3</namecd>
	<common>cream wild indigo</common>
	<spm>
		<spmid>13786</spmid>
		<updttm>
			<month>05</month>
			<day>14</day>
			<year>2001</year>
			<hour>16</hour>
			<min>38</min>
		</updttm>
		<link>http://www.mortonarb.org/vplants/AccLookup?acc=13786</link>
	</spm>
	<spm>
		<spmid>136656</spmid>
		<updttm>
			<month>08</month>
			<day>13</day>
			<year>2000</year>
			<hour>01</hour>
			<min>09</min>
		</updttm>
		<link>http://www.mortonarb.org/vplants/AccLookup?acc=136656</link>
	</spm>
</taxon>
